config/routes.rb
Files::Application.routes.draw do
  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end    
  
  scope "/api/1" do
    get "/files(/*path)" => "files#index"    
    get "/files/*path.:ext" => "files#get"
    put "/files(/*path)" => "files#update"

    resources :movies, :only => [:index, :show, :update]
    resources :downloadables, :only => [:index, :show, :update] do
      get :unconfirmed, :on => :collection
      resources :releases, :only => [:index, :show, :update] do
        get :unconfirmed, :on => :collection
      end
    end
  end

  post "/secret_message" => "dashboard#secret_message"
  get "/stream" => "dashboard#stream", :as => "stream"
  get "/download" => "dashboard#download", :as => "download"
  root :to => "dashboard#index"

end

app/views/layouts/ajax.html.haml
= yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Files
    %link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Neuton:regular,bold", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Cabin:bold", :rel => "stylesheet", :type => "text/css"}
    %link{:rel => "shortcut icon", :href => "/favicon.ico"}
    = include_stylesheets :screen, :media => 'screen, projection'
    = include_stylesheets :print, :media => 'print'
    /[if lt IE 8]
      = include_stylesheets :ie, :media => 'screen, projection'
    - if user_signed_in?
      :javascript
        var FDB = {
          fmt: {},
          Config: {
            assetHost: "#{Files::Config.asset_host}"
          }
        };
      = include_javascripts :main

    = csrf_meta_tag  
  %body(class="#{yield :body_class}")
    #container
      #content
        %header
          %h1 
            = link_to "Files", root_path
          %nav
            - if user_signed_in?
              = link_to "Sign Out", sign_out_path
            - else
              = link_to "Sign In", sign_in_path    
        - [:error, :notice, :success, :alert].select {|f| flash[f].present? }.each do |f|
          %div(class="#{f} flash")
            = flash[f]

        = yield
        #container_footer &nbsp;
    #footer
      %p#secretedit= SystemValue["footer_message"].value